apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: sensorstream-ai
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: sensorstream-raw
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
