#!/bin/bash
PROJECT_NAMESPACE=optaplanner-demo
OPTAPLANNER_APP_NAME=optaplanner-demo
RESOURCE_DIR=$(dirname "$0")

oc project ${PROJECT_NAMESPACE} 2> /dev/null && $RESOURCE_DIR/undeploy.sh || oc new-project ${PROJECT_NAMESPACE}
oc create -f $RESOURCE_DIR/optaplanner-demo-template.yaml

[[ -z "${OPTAPLANNER_REQUEST_CPU}" ]] && { OPTAPLANNER_REQUEST_CPU="4000m"; }
[[ -z "${OPTAPLANNER_REQUEST_MEMORY}" ]] && { OPTAPLANNER_REQUEST_MEMORY="4000Mi"; }
[[ -z "${OPTAPLANNER_LIMIT_CPU}" ]] && { OPTAPLANNER_LIMIT_CPU="4000m"; }
[[ -z "${OPTAPLANNER_LIMIT_MEMORY}" ]] && { OPTAPLANNER_LIMIT_MEMORY="4000Mi"; }

oc new-app --template="${PROJECT_NAMESPACE}/optaplanner-demo" \
  -p CONTAINER_REQUEST_CPU=$OPTAPLANNER_REQUEST_CPU \
  -p CONTAINER_REQUEST_MEMORY=$OPTAPLANNER_REQUEST_MEMORY \
  -p CONTAINER_LIMIT_CPU=$OPTAPLANNER_LIMIT_CPU \
  -p CONTAINER_LIMIT_MEMORY=$OPTAPLANNER_LIMIT_MEMORY

